# This file is generated by gyp; do not edit.

TOOLSET := target
TARGET := jsv8
DEFS_Default := 

# Flags passed to all source files.
CFLAGS_Default := -fPIC -Wall -g3

# Flags passed to only C files.
CFLAGS_C_Default := 

# Flags passed to only C++ files.
CFLAGS_CC_Default := 

INCS_Default := -Ideps/libev-4.11 \
	-Irain-src/include \
	-Ideps/v8/include

OBJS := $(obj).target/$(TARGET)/routine-src/jsv8_routine/jsv8.o \
	$(obj).target/$(TARGET)/routine-src/jsv8_routine/jsv8_main.o \
	$(obj).target/$(TARGET)/routine-src/jsv8_routine/jsv8_ctx.o

# Add to the list of files we specially track dependencies for.
all_deps += $(OBJS)

# Make sure our dependencies are built before any of us.
$(OBJS): | $(obj).target/deps/libev.a

# CFLAGS et al overrides must be target-local.
# See "Target-specific Variable Values" in the GNU Make manual.
$(OBJS): TOOLSET := $(TOOLSET)
$(OBJS): GYP_CFLAGS := $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE)) $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_C_$(BUILDTYPE))
$(OBJS): GYP_CXXFLAGS := $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE)) $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_CC_$(BUILDTYPE))

# Suffix rules, putting all outputs into $(obj).

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(srcdir)/%.cc FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

# Try building from generated source, too.

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj).$(TOOLSET)/%.cc FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj)/%.cc FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

# End of this set of suffix rules
### Rules for final target.
LDFLAGS_Default := -Wl,-E -pg 

LIBS := -lv8

$(obj).target/routine-src/libjsv8.so: GYP_LDFLAGS := $(LDFLAGS_$(BUILDTYPE))
$(obj).target/routine-src/libjsv8.so: LIBS := $(LIBS)
$(obj).target/routine-src/libjsv8.so: LD_INPUTS := $(OBJS) $(obj).target/deps/libev.a
$(obj).target/routine-src/libjsv8.so: TOOLSET := $(TOOLSET)
$(obj).target/routine-src/libjsv8.so: $(OBJS) $(obj).target/deps/libev.a FORCE_DO_CMD
	$(call do_cmd,solink)

all_deps += $(obj).target/routine-src/libjsv8.so
# Add target alias
.PHONY: jsv8
jsv8: $(builddir)/lib.target/libjsv8.so

# Copy this to the shared library output path.
$(builddir)/lib.target/libjsv8.so: TOOLSET := $(TOOLSET)
$(builddir)/lib.target/libjsv8.so: $(obj).target/routine-src/libjsv8.so FORCE_DO_CMD
	$(call do_cmd,copy)

all_deps += $(builddir)/lib.target/libjsv8.so
# Short alias for building this shared library.
.PHONY: libjsv8.so
libjsv8.so: $(obj).target/routine-src/libjsv8.so $(builddir)/lib.target/libjsv8.so

# Add shared library to "all" target.
.PHONY: all
all: $(builddir)/lib.target/libjsv8.so

