# This file is generated by gyp; do not edit.

TOOLSET := target
TARGET := tcpsvr
DEFS_Default := 

# Flags passed to all source files.
CFLAGS_Default := -fPIC -Wall -g3

# Flags passed to only C files.
CFLAGS_C_Default := 

# Flags passed to only C++ files.
CFLAGS_CC_Default := 

INCS_Default := -Ideps/libev-4.11 \
	-Irain-src/include \
	-Iroutine-src/tcpsvr_routine

OBJS := $(obj).target/$(TARGET)/routine-src/tcpsvr_routine/cycle_buffer.o \
	$(obj).target/$(TARGET)/routine-src/tcpsvr_routine/tcpsvr_client.o \
	$(obj).target/$(TARGET)/routine-src/tcpsvr_routine/tcpsvr_main.o \
	$(obj).target/$(TARGET)/routine-src/tcpsvr_routine/tcpsvr_server.o

# Add to the list of files we specially track dependencies for.
all_deps += $(OBJS)

# Make sure our dependencies are built before any of us.
$(OBJS): | $(obj).target/deps/libev.a

# CFLAGS et al overrides must be target-local.
# See "Target-specific Variable Values" in the GNU Make manual.
$(OBJS): TOOLSET := $(TOOLSET)
$(OBJS): GYP_CFLAGS := $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE)) $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_C_$(BUILDTYPE))
$(OBJS): GYP_CXXFLAGS := $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE)) $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_CC_$(BUILDTYPE))

# Suffix rules, putting all outputs into $(obj).

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(srcdir)/%.c FORCE_DO_CMD
	@$(call do_cmd,cc,1)

# Try building from generated source, too.

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj).$(TOOLSET)/%.c FORCE_DO_CMD
	@$(call do_cmd,cc,1)

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj)/%.c FORCE_DO_CMD
	@$(call do_cmd,cc,1)

# End of this set of suffix rules
### Rules for final target.
LDFLAGS_Default := -Wl,-E -pg 

LIBS := 

$(obj).target/routine-src/libtcpsvr.so: GYP_LDFLAGS := $(LDFLAGS_$(BUILDTYPE))
$(obj).target/routine-src/libtcpsvr.so: LIBS := $(LIBS)
$(obj).target/routine-src/libtcpsvr.so: LD_INPUTS := $(OBJS) $(obj).target/deps/libev.a
$(obj).target/routine-src/libtcpsvr.so: TOOLSET := $(TOOLSET)
$(obj).target/routine-src/libtcpsvr.so: $(OBJS) $(obj).target/deps/libev.a FORCE_DO_CMD
	$(call do_cmd,solink)

all_deps += $(obj).target/routine-src/libtcpsvr.so
# Add target alias
.PHONY: tcpsvr
tcpsvr: $(builddir)/lib.target/libtcpsvr.so

# Copy this to the shared library output path.
$(builddir)/lib.target/libtcpsvr.so: TOOLSET := $(TOOLSET)
$(builddir)/lib.target/libtcpsvr.so: $(obj).target/routine-src/libtcpsvr.so FORCE_DO_CMD
	$(call do_cmd,copy)

all_deps += $(builddir)/lib.target/libtcpsvr.so
# Short alias for building this shared library.
.PHONY: libtcpsvr.so
libtcpsvr.so: $(obj).target/routine-src/libtcpsvr.so $(builddir)/lib.target/libtcpsvr.so

# Add shared library to "all" target.
.PHONY: all
all: $(builddir)/lib.target/libtcpsvr.so

