# This file is generated by gyp; do not edit.

TOOLSET := target
TARGET := rain
DEFS_Default := 

# Flags passed to all source files.
CFLAGS_Default :=  -Wall -g3  \
	-pg

# Flags passed to only C files.
CFLAGS_C_Default := 

# Flags passed to only C++ files.
CFLAGS_CC_Default := 

INCS_Default := -Irain-src/src \
	-Irain-src/include

OBJS := $(obj).target/$(TARGET)/rain-src/src/rain_ctx.o \
	$(obj).target/$(TARGET)/rain-src/src/rain_imp.o \
	$(obj).target/$(TARGET)/rain-src/src/rain_lifequeue.o \
	$(obj).target/$(TARGET)/rain-src/src/rain_module.o \
	$(obj).target/$(TARGET)/rain-src/src/rain_queue.o \
	$(obj).target/$(TARGET)/rain-src/src/rain_start.o \
	$(obj).target/$(TARGET)/rain-src/src/rain_rpc.o \
	$(obj).target/$(TARGET)/rain-src/src/rain_array.o \
	$(obj).target/$(TARGET)/rain-src/src/rain_timer.o \
	$(obj).target/$(TARGET)/rain-src/src/rain_loger.o \
	$(obj).target/$(TARGET)/rain-src/src/rain_utils.o

# Add to the list of files we specially track dependencies for.
all_deps += $(OBJS)

# CFLAGS et al overrides must be target-local.
# See "Target-specific Variable Values" in the GNU Make manual.
$(OBJS): TOOLSET := $(TOOLSET)
$(OBJS): GYP_CFLAGS := $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE)) $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_C_$(BUILDTYPE))
$(OBJS): GYP_CXXFLAGS := $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE)) $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_CC_$(BUILDTYPE))

# Suffix rules, putting all outputs into $(obj).

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(srcdir)/%.c FORCE_DO_CMD
	@$(call do_cmd,cc,1)

# Try building from generated source, too.

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj).$(TOOLSET)/%.c FORCE_DO_CMD
	@$(call do_cmd,cc,1)

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj)/%.c FORCE_DO_CMD
	@$(call do_cmd,cc,1)

# End of this set of suffix rules
### Rules for final target.
LDFLAGS_Default := -Wl,-E -pg 

LIBS := -ldl \
	-lpthread \
	-lm

$(builddir)/rain: GYP_LDFLAGS := $(LDFLAGS_$(BUILDTYPE))
$(builddir)/rain: LIBS := $(LIBS)
$(builddir)/rain: LD_INPUTS := $(OBJS)
$(builddir)/rain: TOOLSET := $(TOOLSET)
$(builddir)/rain: $(OBJS) FORCE_DO_CMD
	$(call do_cmd,link)

all_deps += $(builddir)/rain
# Add target alias
.PHONY: rain
rain: $(builddir)/rain

# Add executable to "all" target.
.PHONY: all
all: $(builddir)/rain

